[package]
name = "gbasic-runtime-desktop"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib", "cdylib"]

[features]
default = []
mixer = ["sdl2/mixer"]

[dependencies]
sdl2.workspace = true
